services:
  mysql:
    container_name: mysql
    image: mysql:9
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'someth1ngRe@llySafe!'
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
